name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: macOS-12
    strategy:
      matrix:
        xcode:
          - '14.0.1'
        os:
          - iOS
          - macOS
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
            xcodebuild \
              -project App/Buildkite.xcodeproj \
              -resolvePackageDependencies
            make test-${{ matrix.os }}
