name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  # lints:
  tests:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_12_beta.app
      - name: Bootstrap environment
        run: ./Scripts/bootstrap.sh
      - name: xcodebuild test
        run: |-
          xcodebuild \
            -project Buildkite.xcodeproj \
            -scheme 'iOS' \
            -configuration 'Debug' \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 11' \
            -quiet \
            build test
