name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: macOS-latest
    strategy:
      matrix:
        scheme:
          - iOS
          - macOS
        include:
          - scheme: iOS
            destination: platform=iOS Simulator,OS=latest,name=iPhone 11
          - scheme: macOS
            destination: platform=macOS,arch=x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_12_beta.app
      - name: Bootstrap environment
        env:
          SECRET_BUILDKITE_TOKEN: ${{ secrets.BuildkiteToken }}
        run: ./Scripts/bootstrap.sh
      - name: xcodebuild test
        run: |-
          xcodebuild \
            -project Buildkite.xcodeproj \
            -scheme ${{ matrix.scheme }} \
            -configuration 'Debug' \
            -destination ${{ matrix.destination }} \
            -quiet \
            build
