name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: macOS-11
    strategy:
      matrix:
        scheme:
          - iOS
          - macOS
        include:
          - scheme: iOS
            destination: platform=iOS Simulator,OS=latest,name=iPhone 12 Pro
          - scheme: macOS
            destination: platform=macOS,arch=x86_64
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bootstrap environment
        env:
          SECRET_BUILDKITE_TOKEN: ${{ secrets.BuildkiteToken }}
        run: ./Scripts/bootstrap.sh
      - name: xcodebuild test
        run: |-
          xcodebuild \
            -project Buildkite.xcodeproj \
            -scheme '${{ matrix.scheme }}' \
            -configuration 'Debug' \
            -destination '${{ matrix.destination }}' \
            -quiet \
            build
